apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    release: monitoring
    {{- include "payment-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "payment-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
